package main

import (
	"fmt"
	"strconv"
	"strings"

	metric_opts "github.com/pdcgo/schema/services/selling_iface/v1/metric_opts/v1"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

func main() {
	protogen.Options{}.Run(func(plugin *protogen.Plugin) error {
		for _, file := range plugin.Files {
			if !file.Generate {
				continue
			}
			generateFile(plugin, file)
		}
		return nil
	})
}

// csvField holds the info we need about a field that has a csv_name option.
type csvField struct {
	field    *protogen.Field
	csvName  string // the label from csv_name option
	goName   string // Go getter name e.g. "GetProductName"
	protoKind protoreflect.Kind
}

// collectCsvFields returns fields in a message that have the csv_name extension set.
func collectCsvFields(msg *protogen.Message) []csvField {
	var fields []csvField
	for _, f := range msg.Fields {
		opts, ok := f.Desc.Options().(*descriptorpb.FieldOptions)
		if !ok || opts == nil {
			continue
		}

		if !proto.HasExtension(opts, metric_opts.E_CsvName) {
			continue
		}

		label, ok := proto.GetExtension(opts, metric_opts.E_CsvName).(string)
		if !ok || label == "" {
			continue
		}

		fields = append(fields, csvField{
			field:     f,
			csvName:   label,
			goName:    "Get" + f.GoName,
			protoKind: f.Desc.Kind(),
		})
	}
	return fields
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) {
	// Collect all messages that have at least one csv_name field.
	type msgWithFields struct {
		msg    *protogen.Message
		fields []csvField
	}
	var keep []msgWithFields

	for _, msg := range file.Messages {
		fields := collectCsvFields(msg)
		if len(fields) > 0 {
			keep = append(keep, msgWithFields{msg, fields})
		}
	}

	if len(keep) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_csv.go"
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-csv. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	strconvPkg := protogen.GoImportPath("strconv")
	fmtPkg := protogen.GoImportPath("fmt")

	for _, mf := range keep {
		generateCsvHeaders(g, mf.msg, mf.fields)
		generateCsvValues(g, mf.msg, mf.fields, strconvPkg, fmtPkg)
	}
}

func generateCsvHeaders(g *protogen.GeneratedFile, msg *protogen.Message, fields []csvField) {
	receiver := msg.GoIdent.GoName

	g.P("// CsvHeaders returns the CSV column headers for ", receiver, ".")
	g.P("func (x *", receiver, ") CsvHeaders() []string {")
	g.P("\treturn []string{")
	for _, f := range fields {
		g.P("\t\t", strconv.Quote(f.csvName), ",")
	}
	g.P("\t}")
	g.P("}")
	g.P()
}

func generateCsvValues(g *protogen.GeneratedFile, msg *protogen.Message, fields []csvField, strconvPkg, fmtPkg protogen.GoImportPath) {
	receiver := msg.GoIdent.GoName

	g.P("// CsvValues returns the CSV column values for ", receiver, ".")
	g.P("func (x *", receiver, ") CsvValues() ([]string, error) {")
	g.P("\tif x == nil {")
	g.P("\t\treturn nil, nil")
	g.P("\t}")
	g.P()

	// Build inline slice
	g.P("\treturn []string{")
	for _, f := range fields {
		g.P("\t\t", valueExpr(g, f, strconvPkg, fmtPkg), ",")
	}
	g.P("\t}, nil")
	g.P("}")
	g.P()
}

// valueExpr returns the Go expression that converts a field to a string.
func valueExpr(g *protogen.GeneratedFile, f csvField, strconvPkg, fmtPkg protogen.GoImportPath) string {
	getter := fmt.Sprintf("x.%s()", f.goName)

	switch f.protoKind {
	case protoreflect.StringKind:
		return getter

	case protoreflect.BoolKind:
		formatBool := g.QualifiedGoIdent(protogen.GoIdent{GoName: "FormatBool", GoImportPath: strconvPkg})
		return fmt.Sprintf("%s(%s)", formatBool, getter)

	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		formatInt := g.QualifiedGoIdent(protogen.GoIdent{GoName: "FormatInt", GoImportPath: strconvPkg})
		return fmt.Sprintf("%s(int64(%s), 10)", formatInt, getter)

	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		formatInt := g.QualifiedGoIdent(protogen.GoIdent{GoName: "FormatInt", GoImportPath: strconvPkg})
		return fmt.Sprintf("%s(%s, 10)", formatInt, getter)

	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		formatUint := g.QualifiedGoIdent(protogen.GoIdent{GoName: "FormatUint", GoImportPath: strconvPkg})
		return fmt.Sprintf("%s(uint64(%s), 10)", formatUint, getter)

	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		formatUint := g.QualifiedGoIdent(protogen.GoIdent{GoName: "FormatUint", GoImportPath: strconvPkg})
		return fmt.Sprintf("%s(%s, 10)", formatUint, getter)

	case protoreflect.FloatKind:
		formatFloat := g.QualifiedGoIdent(protogen.GoIdent{GoName: "FormatFloat", GoImportPath: strconvPkg})
		return fmt.Sprintf("%s(float64(%s), 'f', -1, 64)", formatFloat, getter)

	case protoreflect.DoubleKind:
		formatFloat := g.QualifiedGoIdent(protogen.GoIdent{GoName: "FormatFloat", GoImportPath: strconvPkg})
		return fmt.Sprintf("%s(%s, 'f', -1, 64)", formatFloat, getter)

	case protoreflect.EnumKind:
		// Use the enum's String() method
		return fmt.Sprintf("%s.String()", getter)

	case protoreflect.BytesKind:
		return fmt.Sprintf("string(%s)", getter)

	default:
		sprintf := g.QualifiedGoIdent(protogen.GoIdent{GoName: "Sprintf", GoImportPath: fmtPkg})
		return fmt.Sprintf(`%s("%%v", %s)`, sprintf, getter)
	}
}

// cleanComment strips leading "// " from comment lines and joins them.
func cleanComment(s string) string {
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		lines[i] = strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(line), "//"))
	}
	return strings.TrimSpace(strings.Join(lines, " "))
}
