package main

import (
	"fmt"
	"strings"

	"github.com/pdcgo/schema/services/mcp_iface/v1"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	contextPkg = protogen.GoImportPath("context")
	connectPkg = protogen.GoImportPath("connectrpc.com/connect")
	mcpPkg     = protogen.GoImportPath("github.com/modelcontextprotocol/go-sdk/mcp")
	sanMcpPkg  = protogen.GoImportPath("github.com/pdcgo/san_collection/san_mcp")
)

func main() {

	protogen.Options{}.Run(func(plugin *protogen.Plugin) error {
		for _, file := range plugin.Files {
			if !file.Generate || len(file.Services) == 0 {
				continue
			}
			generateFile(plugin, file)
		}
		return nil
	})
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) {
	type serviceWithMethods struct {
		svc     *protogen.Service
		methods []*protogen.Method
	}
	var keep []serviceWithMethods
	for _, svc := range file.Services {
		methods := includedMethods(svc)
		if len(methods) > 0 {
			keep = append(keep, serviceWithMethods{svc, methods})
		}
	}
	if len(keep) == 0 {
		return
	}

	mcpPkgName := string(file.GoPackageName) + "mcp"

	dir := ""
	if i := strings.LastIndex(file.GeneratedFilenamePrefix, "/"); i >= 0 {
		dir = file.GeneratedFilenamePrefix[:i+1]
	}
	base := file.GeneratedFilenamePrefix
	if dir != "" {
		base = file.GeneratedFilenamePrefix[len(dir):]
	}

	filename := dir + mcpPkgName + "/" + base + ".mcp.go"
	importPath := protogen.GoImportPath(string(file.GoImportPath) + "/" + mcpPkgName)

	g := plugin.NewGeneratedFile(filename, importPath)

	g.P("// Code generated by protoc-gen-mcp. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", mcpPkgName)
	g.P()

	connectImportPath := protogen.GoImportPath(string(file.GoImportPath) + "/" + string(file.GoPackageName) + "connect")

	for _, sm := range keep {
		generateService(g, sm.svc, sm.methods, connectImportPath)
	}
}

func includedMethods(svc *protogen.Service) []*protogen.Method {
	var out []*protogen.Method
	for _, m := range svc.Methods {
		if m.Desc.IsStreamingClient() || m.Desc.IsStreamingServer() {
			continue
		}
		opts, _ := m.Desc.Options().(*descriptorpb.MethodOptions)
		if opts == nil {
			continue
		}

		if v, ok := proto.GetExtension(opts, mcp_iface.E_Include).(bool); ok && v {
			out = append(out, m)
		}
	}
	return out
}

func generateService(g *protogen.GeneratedFile, svc *protogen.Service, methods []*protogen.Method, connectImportPath protogen.GoImportPath) {
	connectClientIdent := g.QualifiedGoIdent(protogen.GoIdent{
		GoName:       svc.GoName + "Client",
		GoImportPath: connectImportPath,
	})

	g.P("// Register", svc.GoName, "MCP registers all RPCs of ", svc.GoName, " as MCP tools on server.")
	g.P("func Register", svc.GoName, "MCP(server *", g.QualifiedGoIdent(protogen.GoIdent{GoName: "Server", GoImportPath: mcpPkg}), ", client ", connectClientIdent, ") {")

	for _, method := range methods {
		generateMethod(g, svc, method)
	}

	g.P("}")
	g.P()
}

func generateMethod(g *protogen.GeneratedFile, svc *protogen.Service, method *protogen.Method) {
	toolName := toSnake(svc.GoName) + "_" + toSnake(method.GoName)
	description := strings.TrimSpace(string(method.Comments.Leading))
	if description == "" {
		description = method.GoName
	} else {
		description = cleanComment(description)
	}

	mcpAddTool := g.QualifiedGoIdent(protogen.GoIdent{GoName: "AddTool", GoImportPath: mcpPkg})
	mcpTool := g.QualifiedGoIdent(protogen.GoIdent{GoName: "Tool", GoImportPath: mcpPkg})
	mcpCallToolRequest := g.QualifiedGoIdent(protogen.GoIdent{GoName: "CallToolRequest", GoImportPath: mcpPkg})
	mcpCallToolResult := g.QualifiedGoIdent(protogen.GoIdent{GoName: "CallToolResult", GoImportPath: mcpPkg})
	ctxIdent := g.QualifiedGoIdent(protogen.GoIdent{GoName: "Context", GoImportPath: contextPkg})
	connectNewRequest := g.QualifiedGoIdent(protogen.GoIdent{GoName: "NewRequest", GoImportPath: connectPkg})
	withCallToolRequest := g.QualifiedGoIdent(protogen.GoIdent{GoName: "WithCallToolRequest", GoImportPath: sanMcpPkg})
	requestIdent := g.QualifiedGoIdent(method.Input.GoIdent)

	g.P("\t", mcpAddTool, "(server, &", mcpTool, "{")
	g.P("\t\tName:        ", fmt.Sprintf("%q", toolName), ",")
	g.P("\t\tDescription: ", fmt.Sprintf("%q", description), ",")
	g.P("\t}, func(ctx ", ctxIdent, ", req *", mcpCallToolRequest, ", args *", requestIdent, ") (*", mcpCallToolResult, ", any, error) {")
	g.P("\t\tctx = ", withCallToolRequest, "(ctx, req)")
	g.P("\t\tresp, err := client.", method.GoName, "(ctx, ", connectNewRequest, "(args))")
	g.P("\t\tif err != nil {")
	g.P("\t\t\treturn nil, nil, err")
	g.P("\t\t}")
	g.P("\t\treturn &", mcpCallToolResult, "{}, resp.Msg, nil")
	g.P("\t})")
}

func toSnake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			prev := rune(s[i-1])
			if prev >= 'a' && prev <= 'z' || prev >= '0' && prev <= '9' {
				b.WriteByte('_')
			}
		}
		if r >= 'A' && r <= 'Z' {
			b.WriteRune(r + ('a' - 'A'))
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func cleanComment(s string) string {
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		lines[i] = strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(line), "//"))
	}
	return strings.TrimSpace(strings.Join(lines, " "))
}
